"""S&P500 상위 500개(기존 워치리스트 제외) 확대 스윕.

실거래봇(us_swing_loop)이 실제로 쓰는 전략은 ema_cross 하나뿐이므로, 30전략 x
그리드서치 전체를 다시 돌리는 대신 ema_cross(default 파라미터, 실거래와 동일 조건)만으로
스크리닝한다(app/probe_runner.py의 run_us_ema_cross_probe 재사용) — kr_top200_probe.py와
동일한 이유(대규모 후보군에서 optimize() 그리드서치가 폭발적으로 커져 컨테이너가 죽는 문제 회피).
"""
from __future__ import annotations

from app.probe_runner import run_us_ema_cross_probe

CANDIDATES = [
    ("MMM", "NYS", "3M"),
    ("AOS", "NYS", "A. O. Smith"),
    ("ABT", "NYS", "Abbott Laboratories"),
    ("ABBV", "NYS", "AbbVie"),
    ("ACN", "NYS", "Accenture"),
    ("AES", "NYS", "AES Corporation"),
    ("AFL", "NYS", "Aflac"),
    ("A", "NYS", "Agilent Technologies"),
    ("APD", "NYS", "Air Products"),
    ("ABNB", "NAS", "Airbnb"),
    ("AKAM", "NAS", "Akamai Technologies"),
    ("ALB", "NYS", "Albemarle Corporation"),
    ("ARE", "NYS", "Alexandria Real Estate Equities"),
    ("ALGN", "NAS", "Align Technology"),
    ("ALLE", "NYS", "Allegion"),
    ("LNT", "NAS", "Alliant Energy"),
    ("ALL", "NYS", "Allstate"),
    ("GOOG", "NAS", "Alphabet Inc. (Class C)"),
    ("MO", "NYS", "Altria"),
    ("AMCR", "NYS", "Amcor"),
    ("AEE", "NYS", "Ameren"),
    ("AEP", "NAS", "American Electric Power"),
    ("AXP", "NYS", "American Express"),
    ("AIG", "NYS", "American International Group"),
    ("AMT", "NYS", "American Tower"),
    ("AWK", "NYS", "American Water Works"),
    ("AMP", "NYS", "Ameriprise Financial"),
    ("AME", "NYS", "Ametek"),
    ("AMGN", "NAS", "Amgen"),
    ("APH", "NYS", "Amphenol"),
    ("ADI", "NAS", "Analog Devices"),
    ("AON", "NYS", "Aon plc"),
    ("APA", "NAS", "APA Corporation"),
    ("APO", "NYS", "Apollo Global Management"),
    ("AMAT", "NAS", "Applied Materials"),
    ("APP", "NAS", "AppLovin"),
    ("APTV", "NYS", "Aptiv"),
    ("ACGL", "NAS", "Arch Capital Group"),
    ("ADM", "NYS", "Archer Daniels Midland"),
    ("ARES", "NYS", "Ares Management"),
    ("ANET", "NYS", "Arista Networks"),
    ("AJG", "NYS", "Arthur J. Gallagher & Co."),
    ("AIZ", "NYS", "Assurant"),
    ("ATO", "NYS", "Atmos Energy"),
    ("ADSK", "NAS", "Autodesk"),
    ("ADP", "NAS", "Automatic Data Processing"),
    ("AZO", "NYS", "AutoZone"),
    ("AVY", "NYS", "Avery Dennison"),
    ("AXON", "NAS", "Axon Enterprise"),
    ("BKR", "NAS", "Baker Hughes"),
    ("BALL", "NYS", "Ball Corporation"),
    ("BAX", "NYS", "Baxter International"),
    ("BDX", "NYS", "Becton Dickinson"),
    ("BBY", "NYS", "Best Buy"),
    ("TECH", "NAS", "Bio-Techne"),
    ("BIIB", "NAS", "Biogen"),
    ("BLK", "NYS", "BlackRock"),
    ("BX", "NYS", "Blackstone Inc."),
    ("XYZ", "NYS", "Block, Inc."),
    ("BNY", "NYS", "BNY Mellon"),
    ("BA", "NYS", "Boeing"),
    ("BKNG", "NAS", "Booking Holdings"),
    ("BSX", "NYS", "Boston Scientific"),
    ("BMY", "NYS", "Bristol Myers Squibb"),
    ("AVGO", "NAS", "Broadcom"),
    ("BR", "NYS", "Broadridge Financial Solutions"),
    ("BRO", "NYS", "Brown & Brown"),
    ("BLDR", "NYS", "Builders FirstSource"),
    ("BG", "NYS", "Bunge Global"),
    ("BXP", "NYS", "BXP, Inc."),
    ("CHRW", "NAS", "C.H. Robinson"),
    ("CDNS", "NAS", "Cadence Design Systems"),
    ("CPT", "NYS", "Camden Property Trust"),
    ("COF", "NYS", "Capital One"),
    ("CAH", "NYS", "Cardinal Health"),
    ("CCL", "NYS", "Carnival Corporation"),
    ("CARR", "NYS", "Carrier Global"),
    ("CVNA", "NYS", "Carvana"),
    ("CAT", "NYS", "Caterpillar Inc."),
    ("CBRE", "NYS", "CBRE Group"),
    ("CDW", "NAS", "CDW Corporation"),
    ("COR", "NYS", "Cencora"),
    ("CNC", "NYS", "Centene Corporation"),
    ("CNP", "NYS", "CenterPoint Energy"),
    ("CF", "NYS", "CF Industries"),
    ("CRL", "NYS", "Charles River Laboratories"),
    ("SCHW", "NYS", "Charles Schwab Corporation"),
    ("CHTR", "NAS", "Charter Communications"),
    ("CVX", "NYS", "Chevron Corporation"),
    ("CMG", "NYS", "Chipotle Mexican Grill"),
    ("CB", "NYS", "Chubb Limited"),
    ("CHD", "NYS", "Church & Dwight"),
    ("CIEN", "NYS", "Ciena"),
    ("CI", "NYS", "Cigna"),
    ("CINF", "NAS", "Cincinnati Financial"),
    ("CTAS", "NAS", "Cintas"),
    ("C", "NYS", "Citigroup"),
    ("CFG", "NYS", "Citizens Financial Group"),
    ("CLX", "NYS", "Clorox"),
    ("CME", "NAS", "CME Group"),
    ("CMS", "NYS", "CMS Energy"),
    ("CTSH", "NAS", "Cognizant"),
    ("COHR", "NYS", "Coherent Corp."),
    ("COIN", "NAS", "Coinbase"),
    ("CL", "NYS", "Colgate-Palmolive"),
    ("CMCSA", "NAS", "Comcast"),
    ("COP", "NYS", "ConocoPhillips"),
    ("ED", "NYS", "Consolidated Edison"),
    ("STZ", "NYS", "Constellation Brands"),
    ("CEG", "NAS", "Constellation Energy"),
    ("COO", "NAS", "Cooper Companies (The)"),
    ("CPRT", "NAS", "Copart"),
    ("GLW", "NYS", "Corning Inc."),
    ("CPAY", "NYS", "Corpay"),
    ("CTVA", "NYS", "Corteva"),
    ("CSGP", "NAS", "CoStar Group"),
    ("CRH", "NYS", "CRH plc"),
    ("CRWD", "NAS", "CrowdStrike"),
    ("CCI", "NYS", "Crown Castle"),
    ("CSX", "NAS", "CSX Corporation"),
    ("CMI", "NYS", "Cummins"),
    ("CVS", "NYS", "CVS Health"),
    ("DHR", "NYS", "Danaher Corporation"),
    ("DRI", "NYS", "Darden Restaurants"),
    ("DDOG", "NAS", "Datadog"),
    ("DVA", "NYS", "DaVita"),
    ("DECK", "NYS", "Deckers Brands"),
    ("DE", "NYS", "Deere & Company"),
    ("DELL", "NYS", "Dell Technologies"),
    ("DAL", "NYS", "Delta Air Lines"),
    ("DVN", "NYS", "Devon Energy"),
    ("DXCM", "NAS", "Dexcom"),
    ("FANG", "NAS", "Diamondback Energy"),
    ("DLR", "NYS", "Digital Realty"),
    ("DG", "NYS", "Dollar General"),
    ("DLTR", "NAS", "Dollar Tree"),
    ("D", "NYS", "Dominion Energy"),
    ("DPZ", "NAS", "Domino's"),
    ("DASH", "NAS", "DoorDash"),
    ("DOV", "NYS", "Dover Corporation"),
    ("DOW", "NYS", "Dow Inc."),
    ("DHI", "NYS", "D. R. Horton"),
    ("DTE", "NYS", "DTE Energy"),
    ("DUK", "NYS", "Duke Energy"),
    ("DD", "NYS", "DuPont"),
    ("ETN", "NYS", "Eaton Corporation"),
    ("EBAY", "NAS", "eBay Inc."),
    ("ECHO", "NAS", "EchoStar"),
    ("ECL", "NYS", "Ecolab"),
    ("EIX", "NYS", "Edison International"),
    ("EW", "NYS", "Edwards Lifesciences"),
    ("ELV", "NYS", "Elevance Health"),
    ("EME", "NYS", "Emcor"),
    ("EMR", "NYS", "Emerson Electric"),
    ("ETR", "NYS", "Entergy"),
    ("EOG", "NYS", "EOG Resources"),
    ("EQT", "NYS", "EQT Corporation"),
    ("EFX", "NYS", "Equifax"),
    ("EQIX", "NAS", "Equinix"),
    ("ERIE", "NAS", "Erie Indemnity"),
    ("ESS", "NYS", "Essex Property Trust"),
    ("EL", "NYS", "Estée Lauder Companies (The)"),
    ("EG", "NYS", "Everest Group"),
    ("EVRG", "NAS", "Evergy"),
    ("ES", "NYS", "Eversource Energy"),
    ("EXC", "NAS", "Exelon"),
    ("EXE", "NAS", "Expand Energy"),
    ("EXPE", "NAS", "Expedia Group"),
    ("EXPD", "NYS", "Expeditors International"),
    ("EXR", "NYS", "Extra Space Storage"),
    ("FFIV", "NAS", "F5, Inc."),
    ("FDS", "NYS", "FactSet"),
    ("FICO", "NYS", "Fair Isaac"),
    ("FAST", "NAS", "Fastenal"),
    ("FRT", "NYS", "Federal Realty Investment Trust"),
    ("FDX", "NYS", "FedEx"),
    ("FDXF", "NYS", "FedEx Freight"),
    ("FERG", "NYS", "Ferguson Enterprises"),
    ("FIS", "NYS", "Fidelity National Information Services"),
    ("FITB", "NYS", "Fifth Third Bancorp"),
    ("FSLR", "NAS", "First Solar"),
    ("FE", "NYS", "FirstEnergy"),
    ("FISV", "NAS", "Fiserv"),
    ("FLEX", "NAS", "Flex Ltd."),
    ("F", "NYS", "Ford Motor Company"),
    ("FTNT", "NAS", "Fortinet"),
    ("FTV", "NYS", "Fortive"),
    ("FOXA", "NAS", "Fox Corporation (Class A)"),
    ("FOX", "NAS", "Fox Corporation (Class B)"),
    ("BEN", "NYS", "Franklin Resources"),
    ("FCX", "NYS", "Freeport-McMoRan"),
    ("GRMN", "NYS", "Garmin"),
    ("IT", "NYS", "Gartner"),
    ("GE", "NYS", "GE Aerospace"),
    ("GEHC", "NAS", "GE HealthCare"),
    ("GEV", "NYS", "GE Vernova"),
    ("GEN", "NAS", "Gen Digital"),
    ("GNRC", "NYS", "Generac"),
    ("GD", "NYS", "General Dynamics"),
    ("GIS", "NYS", "General Mills"),
    ("GM", "NYS", "General Motors"),
    ("GPC", "NYS", "Genuine Parts Company"),
    ("GILD", "NAS", "Gilead Sciences"),
    ("GPN", "NYS", "Global Payments"),
    ("GL", "NYS", "Globe Life"),
    ("GDDY", "NYS", "GoDaddy"),
    ("GS", "NYS", "Goldman Sachs"),
    ("HAL", "NYS", "Halliburton"),
    ("HIG", "NYS", "Hartford (The)"),
    ("HAS", "NAS", "Hasbro"),
    ("HCA", "NYS", "HCA Healthcare"),
    ("DOC", "NYS", "Healthpeak Properties"),
    ("HSIC", "NAS", "Henry Schein"),
    ("HSY", "NYS", "Hershey Company (The)"),
    ("HPE", "NYS", "Hewlett Packard Enterprise"),
    ("HLT", "NYS", "Hilton Worldwide"),
    ("HONA", "NAS", "Honeywell Aerospace"),
    ("HON", "NAS", "Honeywell Technologies"),
    ("HRL", "NYS", "Hormel Foods"),
    ("HST", "NAS", "Host Hotels & Resorts"),
    ("HWM", "NYS", "Howmet Aerospace"),
    ("HPQ", "NYS", "HP Inc."),
    ("HUBB", "NYS", "Hubbell Incorporated"),
    ("HUM", "NYS", "Humana"),
    ("HII", "NYS", "Huntington Ingalls Industries"),
    ("IBM", "NYS", "IBM"),
    ("IEX", "NYS", "IDEX Corporation"),
    ("IDXX", "NAS", "Idexx Laboratories"),
    ("ITW", "NYS", "Illinois Tool Works"),
    ("INCY", "NAS", "Incyte"),
    ("IR", "NYS", "Ingersoll Rand"),
    ("PODD", "NAS", "Insulet Corporation"),
    ("IBKR", "NAS", "Interactive Brokers"),
    ("ICE", "NYS", "Intercontinental Exchange"),
    ("IFF", "NYS", "International Flavors & Fragrances"),
    ("IP", "NYS", "International Paper"),
    ("INTU", "NAS", "Intuit"),
    ("ISRG", "NAS", "Intuitive Surgical"),
    ("IVZ", "NYS", "Invesco"),
    ("INVH", "NYS", "Invitation Homes"),
    ("IQV", "NYS", "IQVIA"),
    ("IRM", "NYS", "Iron Mountain"),
    ("JBHT", "NAS", "J.B. Hunt"),
    ("JBL", "NYS", "Jabil"),
    ("JKHY", "NAS", "Jack Henry & Associates"),
    ("J", "NYS", "Jacobs Solutions"),
    ("JCI", "NYS", "Johnson Controls"),
    ("KVUE", "NYS", "Kenvue"),
    ("KDP", "NAS", "Keurig Dr Pepper"),
    ("KEYS", "NYS", "Keysight Technologies"),
    ("KMB", "NAS", "Kimberly-Clark"),
    ("KIM", "NYS", "Kimco Realty"),
    ("KKR", "NYS", "KKR & Co."),
    ("KLAC", "NAS", "KLA Corporation"),
    ("KHC", "NAS", "Kraft Heinz"),
    ("KR", "NYS", "Kroger"),
    ("LHX", "NYS", "L3Harris"),
    ("LH", "NYS", "Labcorp"),
    ("LRCX", "NAS", "Lam Research"),
    ("LVS", "NYS", "Las Vegas Sands"),
    ("LDOS", "NYS", "Leidos"),
    ("LEN", "NYS", "Lennar"),
    ("LII", "NYS", "Lennox International"),
    ("LLY", "NYS", "Lilly (Eli)"),
    ("LIN", "NAS", "Linde plc"),
    ("LYV", "NYS", "Live Nation Entertainment"),
    ("LMT", "NYS", "Lockheed Martin"),
    ("L", "NYS", "Loews Corporation"),
    ("LOW", "NYS", "Lowe's"),
    ("LULU", "NAS", "Lululemon Athletica"),
    ("LITE", "NAS", "Lumentum"),
    ("LYB", "NYS", "LyondellBasell"),
    ("MTB", "NYS", "M&T Bank"),
    ("MPC", "NYS", "Marathon Petroleum"),
    ("MAR", "NAS", "Marriott International"),
    ("MRSH", "NYS", "Marsh McLennan"),
    ("MLM", "NYS", "Martin Marietta Materials"),
    ("MRVL", "NAS", "Marvell Technology"),
    ("MAS", "NYS", "Masco"),
    ("MKC", "NYS", "McCormick & Company"),
    ("MCD", "NYS", "McDonald's"),
    ("MCK", "NYS", "McKesson Corporation"),
    ("MDT", "NYS", "Medtronic"),
    ("MRK", "NYS", "Merck & Co."),
    ("MET", "NYS", "MetLife"),
    ("MTD", "NYS", "Mettler Toledo"),
    ("MGM", "NYS", "MGM Resorts"),
    ("MCHP", "NAS", "Microchip Technology"),
    ("MU", "NAS", "Micron Technology"),
    ("MAA", "NYS", "Mid-America Apartment Communities"),
    ("MRNA", "NAS", "Moderna"),
    ("TAP", "NYS", "Molson Coors Beverage Company"),
    ("MDLZ", "NAS", "Mondelez International"),
    ("MPWR", "NAS", "Monolithic Power Systems"),
    ("MNST", "NAS", "Monster Beverage"),
    ("MCO", "NYS", "Moody's Corporation"),
    ("MS", "NYS", "Morgan Stanley"),
    ("MOS", "NYS", "Mosaic Company (The)"),
    ("MSI", "NYS", "Motorola Solutions"),
    ("MSCI", "NYS", "MSCI"),
    ("NDAQ", "NAS", "Nasdaq, Inc."),
    ("NTAP", "NAS", "NetApp"),
    ("NEM", "NYS", "Newmont"),
    ("NWSA", "NAS", "News Corp (Class A)"),
    ("NWS", "NAS", "News Corp (Class B)"),
    ("NEE", "NYS", "NextEra Energy"),
    ("NKE", "NYS", "Nike, Inc."),
    ("NI", "NYS", "NiSource"),
    ("NDSN", "NAS", "Nordson Corporation"),
    ("NSC", "NYS", "Norfolk Southern"),
    ("NTRS", "NAS", "Northern Trust"),
    ("NOC", "NYS", "Northrop Grumman"),
    ("NCLH", "NYS", "Norwegian Cruise Line Holdings"),
    ("NRG", "NYS", "NRG Energy"),
    ("NUE", "NYS", "Nucor"),
    ("NVR", "NYS", "NVR, Inc."),
    ("NXPI", "NAS", "NXP Semiconductors"),
    ("ORLY", "NAS", "O'Reilly Automotive"),
    ("OXY", "NYS", "Occidental Petroleum"),
    ("ODFL", "NAS", "Old Dominion"),
    ("OMC", "NYS", "Omnicom Group"),
    ("ON", "NAS", "ON Semiconductor"),
    ("OKE", "NYS", "Oneok"),
    ("ORCL", "NYS", "Oracle Corporation"),
    ("OTIS", "NYS", "Otis Worldwide"),
    ("PCAR", "NAS", "Paccar"),
    ("PKG", "NYS", "Packaging Corporation of America"),
    ("PLTR", "NAS", "Palantir Technologies"),
    ("PANW", "NAS", "Palo Alto Networks"),
    ("PSKY", "NAS", "Paramount Skydance Corporation"),
    ("PH", "NYS", "Parker Hannifin"),
    ("PAYX", "NAS", "Paychex"),
    ("PYPL", "NAS", "PayPal"),
    ("PNR", "NYS", "Pentair"),
    ("PFE", "NYS", "Pfizer"),
    ("PCG", "NYS", "PG&E Corporation"),
    ("PM", "NYS", "Philip Morris International"),
    ("PSX", "NYS", "Phillips 66"),
    ("PNW", "NYS", "Pinnacle West Capital"),
    ("PNC", "NYS", "PNC Financial Services"),
    ("PPG", "NYS", "PPG Industries"),
    ("PPL", "NYS", "PPL Corporation"),
    ("PFG", "NAS", "Principal Financial Group"),
    ("PGR", "NYS", "Progressive Corporation"),
    ("PLD", "NYS", "Prologis"),
    ("PRU", "NYS", "Prudential Financial"),
    ("PEG", "NYS", "Public Service Enterprise Group"),
    ("PTC", "NAS", "PTC Inc."),
    ("PSA", "NYS", "Public Storage"),
    ("PHM", "NYS", "PulteGroup"),
    ("PWR", "NYS", "Quanta Services"),
    ("DGX", "NYS", "Quest Diagnostics"),
    ("Q", "NYS", "Qnity Electronics"),
    ("RL", "NYS", "Ralph Lauren Corporation"),
    ("RJF", "NYS", "Raymond James Financial"),
    ("RDDT", "NYS", "Reddit"),
    ("RTX", "NYS", "RTX Corporation"),
    ("O", "NYS", "Realty Income"),
    ("REG", "NAS", "Regency Centers"),
    ("REGN", "NAS", "Regeneron Pharmaceuticals"),
    ("RSG", "NYS", "Republic Services"),
    ("RMD", "NYS", "ResMed|"),
    ("RVTY", "NYS", "Revvity"),
    ("HOOD", "NAS", "Robinhood Markets"),
    ("ROK", "NYS", "Rockwell Automation"),
    ("ROL", "NYS", "Rollins, Inc."),
    ("ROP", "NAS", "Roper Technologies"),
    ("ROST", "NAS", "Ross Stores"),
    ("RCL", "NYS", "Royal Caribbean Group"),
    ("SPGI", "NYS", "S&P Global"),
    ("CRM", "NYS", "Salesforce"),
    ("SNDK", "NAS", "Sandisk"),
    ("SBAC", "NAS", "SBA Communications"),
    ("SLB", "NYS", "Schlumberger"),
    ("STX", "NAS", "Seagate Technology"),
    ("SRE", "NYS", "Sempra"),
    ("NOW", "NYS", "ServiceNow"),
    ("SHW", "NYS", "Sherwin-Williams"),
    ("SPG", "NYS", "Simon Property Group"),
    ("SWKS", "NAS", "Skyworks Solutions"),
    ("SJM", "NYS", "J.M. Smucker Company (The)"),
    ("SW", "NYS", "Smurfit Westrock"),
    ("SNA", "NYS", "Snap-on"),
    ("SOLV", "NYS", "Solventum"),
    ("SO", "NYS", "Southern Company"),
    ("LUV", "NYS", "Southwest Airlines"),
    ("SWK", "NYS", "Stanley Black & Decker"),
    ("SBUX", "NAS", "Starbucks"),
    ("STT", "NYS", "State Street Corporation"),
    ("STLD", "NAS", "Steel Dynamics"),
    ("STE", "NYS", "Steris"),
    ("SYK", "NYS", "Stryker Corporation"),
    ("SMCI", "NAS", "Supermicro"),
    ("SYF", "NYS", "Synchrony Financial"),
    ("SNPS", "NAS", "Synopsys"),
    ("SYY", "NYS", "Sysco"),
    ("TMUS", "NAS", "T-Mobile US"),
    ("TROW", "NAS", "T. Rowe Price"),
    ("TTWO", "NAS", "Take-Two Interactive"),
    ("TPR", "NYS", "Tapestry, Inc."),
    ("TRGP", "NYS", "Targa Resources"),
    ("TGT", "NYS", "Target Corporation"),
    ("TEL", "NYS", "TE Connectivity"),
    ("TDY", "NYS", "Teledyne Technologies"),
    ("TER", "NAS", "Teradyne"),
    ("TXN", "NAS", "Texas Instruments"),
    ("TPL", "NYS", "Texas Pacific Land Corporation"),
    ("TXT", "NYS", "Textron"),
    ("TMO", "NYS", "Thermo Fisher Scientific"),
    ("TJX", "NYS", "TJX Companies"),
    ("TKO", "NYS", "TKO Group Holdings"),
    ("TTD", "NAS", "Trade Desk (The)"),
    ("TSCO", "NAS", "Tractor Supply"),
    ("TT", "NYS", "Trane Technologies"),
    ("TDG", "NYS", "TransDigm Group"),
    ("TRV", "NYS", "Travelers Companies (The)"),
    ("TRMB", "NAS", "Trimble Inc."),
    ("TFC", "NYS", "Truist Financial"),
    ("TYL", "NYS", "Tyler Technologies"),
    ("TSN", "NYS", "Tyson Foods"),
    ("USB", "NYS", "U.S. Bancorp"),
    ("UBER", "NYS", "Uber"),
    ("UDR", "NYS", "UDR, Inc."),
    ("ULTA", "NAS", "Ulta Beauty"),
    ("UNP", "NYS", "Union Pacific Corporation"),
    ("UAL", "NAS", "United Airlines Holdings"),
    ("UPS", "NYS", "United Parcel Service"),
    ("URI", "NYS", "United Rentals"),
    ("UHS", "NYS", "Universal Health Services"),
    ("VLO", "NYS", "Valero Energy"),
    ("VEEV", "NYS", "Veeva Systems"),
    ("VTR", "NYS", "Ventas"),
    ("VLTO", "NYS", "Veralto"),
    ("VRSN", "NAS", "Verisign"),
    ("VRSK", "NAS", "Verisk Analytics"),
    ("VZ", "NYS", "Verizon"),
    ("VRTX", "NAS", "Vertex Pharmaceuticals"),
    ("VRT", "NYS", "Vertiv"),
    ("VTRS", "NAS", "Viatris"),
    ("VICI", "NYS", "Vici Properties"),
    ("VST", "NYS", "Vistra Corp."),
    ("VMRK", "NYS", "Vivmark Residential"),
    ("VMC", "NYS", "Vulcan Materials Company"),
    ("WRB", "NYS", "W. R. Berkley Corporation"),
    ("GWW", "NYS", "W. W. Grainger"),
    ("WAB", "NYS", "Wabtec"),
    ("WBD", "NAS", "Warner Bros. Discovery"),
    ("WM", "NYS", "Waste Management"),
    ("WAT", "NYS", "Waters Corporation"),
    ("WEC", "NYS", "WEC Energy Group"),
    ("WFC", "NYS", "Wells Fargo"),
    ("WELL", "NYS", "Welltower"),
    ("WST", "NYS", "West Pharmaceutical Services"),
    ("WDC", "NAS", "Western Digital"),
    ("WY", "NYS", "Weyerhaeuser"),
    ("WSM", "NYS", "Williams-Sonoma, Inc."),
    ("WMB", "NYS", "Williams Companies"),
    ("WTW", "NAS", "Willis Towers Watson"),
    ("WDAY", "NAS", "Workday, Inc."),
    ("WYNN", "NAS", "Wynn Resorts"),
    ("XEL", "NAS", "Xcel Energy"),
    ("XYL", "NYS", "Xylem Inc."),
    ("YUM", "NYS", "Yum! Brands"),
    ("ZBRA", "NAS", "Zebra Technologies"),
    ("ZBH", "NYS", "Zimmer Biomet"),
    ("ZTS", "NYS", "Zoetis"),
]

def run() -> None:
    run_us_ema_cross_probe(CANDIDATES)


if __name__ == "__main__":
    run()
